# Generated by Django 3.0.6 on 2020-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20200617_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Like New', 'LikeNew'), ('Good Condition', 'GoodCondition'), ('Bad Condition', 'BadCondition')], max_length=15, null=True),
        ),
    ]
