# Generated by Django 3.0.6 on 2020-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_auto_20200722_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
