# Generated by Django 3.0.6 on 2020-05-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
